### PR TITLE
Please consider the following script to replace 'extract-pw.py'.

### PR DESCRIPTION
**Pull request by dkarpo**

### CODE REVIEW

**Comment by fduraibi** [comment]
@dkarpo you are right, my bad. I didn't actually try it, instead it looked wrong so I "fixed" it (or that what i thought) and used the hex format. But I just tested it again and your output works great.

It would make sense if you can also print out the whole command so the user will simply cut and paste like this:

```
sudo hdparm --security-disable $(printf '\x19\x18\x11\x12\x13\x032\x12\x00.....') /dev/yourdrive
```
Also i believe you can remove the trailing zeros since they are for padding only.

**Comment by fduraibi** [comment]
The author is around. @BlackLotus just responded to a pull request which I suggested.

**Comment by BlackLotus** [comment]
The great thing about git is that you don't need "the author", but yeah I'm here.
I was proofreading the code the first time it was submitted, I think I planned on merging it (have to proofread it again), but life got in the way.
Am working on too many projects right now, so I don't really have the time to do everything, but since I'm reviving a few of my old projects anyway sure.
Oh btw thank you dkarpo for the commit, sorry I didn't respond in over a year.

**Comment by fduraibi** [comment]
sure you can fork it and fix your fork, but sometimes you like to contribute back to the main repo, specially since your code with @dkarpo update helped me recover my drive.

This is not related, but isn't the user password the same as the HDD password that we set through the BIOS?, since the password that I had on my drive (which i still remember) consists of only 10 ASCII characters (9 letters and 1 digit), while the one I extracted is only 8 bytes and only 1 of them is a printable character!

**Pull request merged**
